#!/usr/bin/env bash

get_hrefs () {
    local url="$1"
    local regexp="$2"
    local download_cmd

    if command -v wget >/dev/null 2>&1; then
        download_cmd="wget -q -O-"
    elif command -v curl >/dev/null 2>&1; then
        download_cmd="curl -s -o-"
    else
        echo "ERROR: Neither wget or curl is available, unable to perform download"
        exit 1
    fi

    $download_cmd "${url}" | sed -E "s/></>\n</g" | sed -n -E "s|^.*<a href=\"(${regexp})\">.*|\1|p" | uniq
}

BUILD_ARGS=("$@")
BUILD_CMD="docker build"
DOCKER_REPO="${DOCKER_REPO:-docker-wine}"
URL="https://dl.winehq.org/wine-builds/ubuntu/dists/"

# Get the latest Ubuntu version codename that Wine is available on
UBUNTU_CODENAME=$(get_hrefs "${URL}" "[^:]+/" | sed -E "s|/$||" | grep -v -E "^([p-z]|/)" | sort -r | head -1)

# Just use latest tag if unable to be determined
if [ -n "${UBUNTU_CODENAME}" ]; then
    echo "Found Wine is available on Ubuntu ${UBUNTU_CODENAME}"
    TAG="ubuntu-${UBUNTU_CODENAME}"
else
    echo "WARNING: Unable to determine version of Ubuntu to use with Wine, so using latest"
    TAG="latest"
fi

if ! docker -v >/dev/null 2>&1; then
    if buildah -v >/dev/null 2>&1; then
        BUILD_CMD="buildah bud"
    else
        echo "ERROR: Docker is not running or not installed, unable to proceed"
        exit 1
    fi
fi

${BUILD_CMD} "${BUILD_ARGS[@]}" --build-arg="TAG=${TAG}" -t "${DOCKER_REPO}" .
