#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
branch=$(echo $branch | perl -pe 's/\//-/g')
branch=$(echo -$branch)
branch=$(echo $branch | perl -pe 's/-main//')

if [[ $1 == "--rm" ]]; then
    shift
    $0 "$@"
    exitcode=$?
    docker rm winehome${branch}
    exit $exitcode
fi

if ! docker ps -a | grep -q winehome${branch}; then
    docker create \
        --volume="/wine" \
        --name="winehome${branch}" \
        docker-wine${branch} \
        /bin/true
fi

docker run -it \
    --rm \
    --env="DISPLAY" \
    --env="USER" \
    --volume="/etc/group:/etc/group:ro" \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/shadow:/etc/shadow:ro" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
    --volumes-from="winehome${branch}" \
    --name=wine${branch} \
    docker-wine${branch} $*
