#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)
branch=$(echo $branch | perl -pe 's/\//-/g')
branch=$(echo -$branch)
branch=$(echo $branch | perl -pe 's/-master//')

case $1 in
    --rm)
        echo "Auto-removing volume container 'winehome${branch}' after completing action..."
        shift
        $0 "$@"
        exitcode=$?
        docker volume rm winehome${branch} 2>&1 >/dev/null
        echo "Removed 'winehome${branch}' volume container"
        exit $exitcode
        ;;
    --help)
        echo "Usage: $0 [--rm] [command] [arguments]..."
        echo "e.g."
        echo "    $0"
        echo "    $0 --rm"
        echo "    $0 wineboot --init"
        echo "    $0 --rm wine explorer.exe"
        exit 0
        ;;
esac

if ! docker volume ls -qf "name=winehome${branch}" | grep -q "winehome${branch}"; then
    echo "Creating volume container 'winehome${branch}'..."
    docker volume create winehome${branch}
else
    echo "Using existing volume container 'winehome${branch}'..."
fi

docker run -it \
    --rm \
    --env="DISPLAY" \
    --volume="$HOME/.Xauthority:/home/wine/.Xauthority:ro" \
    --volume="winehome${branch}:/home/wine" \
    --net="host" \
    --name="wine${branch}" \
    docker-wine${branch} $*
