#!/bin/bash

source build_args/ubuntu-stable

echo "GECKO_VER  = $GECKO_VER"
echo "IMAGE_VER  = $(cat VERSION)"
echo "MONO_VER   = $MONO_VER"
echo "WINE_VER   = $WINE_VER"
echo "WINEBRANCH = $WINEBRANCH"

docker build \
    --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
    --build-arg GECKO_VER=$GECKO_VER \
    --build-arg GIT_REV=$SOURCE_COMMIT \
    --build-arg IMAGE_VER=$(cat VERSION) \
    --build-arg MONO_VER=$MONO_VER \
    --build-arg WINE_VER=$WINE_VER \
    --build-arg WINEBRANCH=$WINEBRANCH \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
