#!/bin/bash

source build_args/ubuntu-stable
VERSION=$(cat VERSION)

if [ "$SOURCE_BRANCH" == "dev" ]; then
    docker tag $IMAGE_NAME ${DOCKER_REPO}:dev-${WINEBRANCH}-${VERSION}
    docker push ${DOCKER_REPO}:dev-${WINEBRANCH}-${VERSION}
else
    docker tag $IMAGE_NAME ${DOCKER_REPO}:latest
    docker push ${DOCKER_REPO}:latest
    docker tag $IMAGE_NAME ${DOCKER_REPO}:${WINEBRANCH}-${VERSION}
    docker push ${DOCKER_REPO}:${WINEBRANCH}-${VERSION}
fi
