#!/usr/bin/env bash

# This file should be copied to <repo root>/.git/hooks/pre-commit to enable pre-commit checks

# Redirect output to stderr
exec 1>&2

# Check shellcheck available
if ! command -v shellcheck >/dev/null 2>&1; then
    echo "ERROR: shellcheck does not appear to be installed"
    exit 1
fi

# Run shellcheck on all shell files
for FILE in $(git diff --cached --name-only); do
    if head -1 "${FILE}" | grep -q -E "^#!.*sh$"; then
        shellcheck "${FILE}" || exit 1
    fi
done
